---
- import_playbook: includes/ensure_host_keys.yml

- name: VOLTTRON Status
  hosts: all
  tasks:
    - include_tasks: includes/common.yml

    - include_tasks: includes/update_facts.yml

    - name: Retrieving Status
      volttron_instance_config:
        config_file: "{{ host_config }}"
      check_mode: True
      register: instance_state
      ignore_errors: yes
    - name: retrieve status error print
      when: instance_state.failed
      debug:
        msg: "{{ instance_state.msg.split('\\n') }}"
      failed_when: true

    ##TODO: something is wrong in the current/expected state comparison,
    #       it shows that it will change when it should not
    ##TODO: installed historian is not running but reported state is RUNNING
    - name: display instance states
      debug:
        var: instance_state
