---
- import_playbook: includes/ensure_host_keys.yml

# Running this allows us to set the variables that are going to be used in the
# environment block before the execution of the second play.
- name: environmental setup
  hosts: all
  tasks:
    - include_tasks: includes/defaults.yml

- name: Start VOLTTRON
  hosts: all
  gather_facts: True
  tasks:
    - include_tasks: includes/common.yml

    - include_tasks: includes/copy_configs.yml

    - name: Configure VOLTTRON instance (agent install phase)
      volttron_instance_config:
        volttron_home: "{{ volttron_home }}"
        config_file: "{{ host_config }}"
        state: "RUNNING"
        phase: "AGENT_INSTALL"
        # This variable must be passed on for the module to be able to be used
        # if using the vctl deploy script this variable is created via extra_vars
        volttron_host_facts: "{{ volttron_host_facts }}"
      ignore_errors: yes
      register: agent_install_result
    - name: agent install error diagnostics
      when: agent_install_result.failed
      debug:
        msg: "{{ agent_install_result.msg.split('\\n') }}"
      failed_when: True

    - name: Configure VOLTTRON instance (external connection phase)
      volttron_instance_config:
        config_file: "{{ host_config }}"
        state: "RUNNING"
        phase: "ALLOW_EXTERNAL_CONNECTIONS"
        # This variable must be passed on for the module to be able to be used
        # if using the vctl deploy script this variable is created via extra_vars
        volttron_host_facts: "{{ volttron_host_facts }}"

    - name: Configure VOLTTRON instance (start agents phase)
      volttron_instance_config:
        config_file: "{{ host_config }}"
        state: "RUNNING"
        phase: "START_AGENTS"
        # This variable must be passed on for the module to be able to be used
        # if using the vctl deploy script this variable is created via extra_vars
        volttron_host_facts: "{{ volttron_host_facts }}"

