---
- name: Retrieving Status
  volttron_instance_config:
    config_file: "{{ host_config }}"
  check_mode: True
  # Used in instance.fact template below
  register: my_state
  ignore_errors: yes
- name: retrieving status print error
  when: my_state.failed and 'module_stdout' in my_state
  debug:
    msg: "{{ my_state.module_stdout.split('\n') }}"
  failed_when: true
- name: retrieving status print error
  when: my_state.failed and 'msg' in my_state
  debug:
    msg: "{{ my_state.msg.split('\n') }}"
  failed_when: true
- name: retrieving status print error
  when: my_state.failed
  debug:
    msg: "expected output fields not found, full return is: {{my_state}}"
  failed_when: true

- name: Create fact file
  template:
    owner: "{{ ansible_user }}"
    src: templates/instance.fact
    dest: /etc/ansible/facts.d/instance.fact
