---
- name: Retrieving Status
  volttron_instance_config:
    config_file: "{{ host_config }}"
  check_mode: True
  # Used in instance.fact template below
  register: my_state
  ignore_errors: yes
- name: retrieving status print error
  when: my_state.failed
  debug:
    msg: "{{ my_state.module_stdout.split('\r\n') }}"
  failed_when: true

- name: Create fact file
  template:
    owner: "{{ ansible_user }}"
    src: templates/instance.fact
    dest: /etc/ansible/facts.d/instance.fact
